# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 60%
        threshold: 5%

# Ignore paths from coverage calculation
ignore:
  - "examples/**/*"
  - "cmd/**/*"

# Go-specific parser settings
parsers:
  go:
    partials_as_hits: false

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
