package raster

import (
	"fmt"
	"image"
	"image/color"
	"testing"
)

// TestMultiContourStrokeFillGolden verifies our rasterizer produces
// deterministic, pixel-exact output for a multi-contour stroke-expanded
// path (outer CW + inner CCW, NonZero fill rule).
//
// The golden image was generated by our own rasterizer. Any change in
// coverage output will be caught as a regression.
func TestMultiContourStrokeFillGolden(t *testing.T) {
	got := renderMultiContourFolder(20, 20)
	golden := loadGoldenPNG(t, "multicontour-fill-20x20.png")
	result := compareImages(got, golden)
	logCompareResult(t, "multi-contour stroke fill (regression)", result)

	if result.DiffCount > 0 {
		t.Errorf("regression: %d pixels differ (max_diff=%d), want exact match",
			result.DiffCount, result.MaxDiff)
	}
}

// TestMultiContourVsSkiaAAA compares our output against Skia AAA golden
// (generated via fiddle.skia.org, hash 787e4807f1d8e445a262180d3a9c5578)
// with per-pixel exact diff verification.
//
// Every differing pixel is accounted for in expectedSkiaDiffR. The test
// fails if ANY pixel has an unexpected diff or a known diff changes value.
// This catches both regressions and unintended improvements.
//
// Root cause of diffs: different quad curve evaluation methods.
//   - Ours: recursive De Casteljau subdivision (0.1px tolerance, float).
//     Chosen for stability — FDot6 forward-diff produced zero-height
//     segments that lost winding contribution (issue #148, v0.32.3).
//   - Skia: FDot6 forward-differencing (O(1)/step, 1/8px accuracy).
//     Chosen for performance — O(1) per edge step, cache-friendly.
//
// Ground truth (200×200 supersample) shows our coverage is closer to
// mathematical truth: max|ours−GT|=21 vs max|skia−GT|=31.
// All 21 diffs are on QuadTo curve corners. Straight edges: diff==0.
func TestMultiContourVsSkiaAAA(t *testing.T) {
	// Exact per-pixel expected diff (our R − Skia R).
	// Positive = our coverage higher, negative = lower.
	// All entries are on QuadTo curve corners where geometric flattening
	// (ours) and FDot6 forward-differencing (Skia) produce different
	// sub-pixel edge positions.
	expectedSkiaDiffR := map[[2]int]int{
		// Top-left corner (outer QuadTo 1.25,2.75→3.25,2.75 + inner 2.25,3.75→...)
		{2, 2}: +3, {1, 3}: +8, {2, 3}: -5, {1, 4}: +7, {2, 4}: +5,
		// Tab notch diagonal (LineTo 10.84,5.19→11.05,5.37 + QuadTo curves)
		{9, 4}: -1,
		// Top-right corner (outer QuadTo 18.75,5.25→18.75,7)
		{17, 5}: +25, {18, 5}: +6, {17, 6}: -8, {18, 6}: +12,
		// Bottom-left corner (outer QuadTo 1.25,17.25→1.25,15.17)
		{1, 15}: +7, {2, 15}: -5, {1, 16}: +8, {2, 16}: -6,
		// Bottom-right corner (outer QuadTo 18.75,17.25→16.75,17.25)
		{17, 15}: -5, {18, 15}: +7, {17, 16}: -6, {18, 16}: +8,
		// Bottom edge (outer QuadTo endpoints)
		{2, 17}: +3, {3, 17}: -1, {17, 17}: +3,
	}

	got := renderMultiContourFolder(20, 20)
	skia := loadGoldenPNG(t, "stroke-expanded-fill-20x20.png")
	w, h := 20, 20
	failed := false

	for y := range h {
		for x := range w {
			ourR := int(got.RGBAAt(x, y).R)
			skiaR := int(skia.RGBAAt(x, y).R)
			actualDiff := ourR - skiaR

			expected, known := expectedSkiaDiffR[[2]int{x, y}]
			if known {
				if actualDiff != expected {
					t.Errorf("(%d,%d): diff changed: got %+d, expected %+d", x, y, actualDiff, expected)
					failed = true
				}
			} else if actualDiff != 0 {
				t.Errorf("(%d,%d): unexpected diff %+d (not in known diff table)", x, y, actualDiff)
				failed = true
			}
		}
	}

	if !failed {
		t.Logf("PASS: all %d known Skia AAA diffs match exactly (max R diff: 25)", len(expectedSkiaDiffR))
	}
}

func TestMultiContourCoverageDump(t *testing.T) {
	path := buildExpandedFolderPath()

	w, h := 20, 20
	eb := NewEdgeBuilder(2)
	eb.SetFlattenCurves(true)
	eb.BuildFromPath(path, IdentityTransform{})

	coverageBuf := make([]uint8, w*h)
	FillToBuffer(eb, w, h, FillRuleNonZero, coverageBuf)

	t.Log("Coverage map (hex):")
	for y := range h {
		row := ""
		for x := range w {
			c := coverageBuf[y*w+x]
			if c == 0 {
				row += "  ."
			} else {
				row += fmt.Sprintf(" %02X", c)
			}
		}
		t.Logf("  y%02d:%s", y, row)
	}
}

// --- Forward-diff (flatten=false) golden tests ---

// TestMultiContourCurveGolden verifies forward-diff curve edge rendering
// is deterministic and pixel-exact. Golden generated by our rasterizer
// with SetFlattenCurves(false) — native QuadraticEdge forward-differencing.
func TestMultiContourCurveGolden(t *testing.T) {
	got := renderMultiContourFolderCurve(20, 20)
	golden := loadGoldenPNG(t, "multicontour-curve-20x20.png")
	result := compareImages(got, golden)
	logCompareResult(t, "multi-contour curve mode (regression)", result)

	if result.DiffCount > 0 {
		t.Errorf("regression: %d pixels differ (max_diff=%d), want exact match",
			result.DiffCount, result.MaxDiff)
	}
}

// TestMultiContourCurveVsSkiaAAA compares forward-diff output against Skia
// AAA golden with per-pixel exact diff verification.
//
// Forward-diff mode with deviation-based subdivision (0.1px threshold) produces
// 23 differing pixels (max 25) vs Skia. All diffs are on QuadTo curve corners
// where our deviation-based subdivision and Skia's FDot6 forward-differencing
// produce slightly different sub-pixel edge positions.
func TestMultiContourCurveVsSkiaAAA(t *testing.T) {
	expectedDiffR := map[[2]int]int{
		{2, 2}: +10, {3, 2}: +2, {7, 2}: +5,
		{1, 3}: +11, {2, 3}: -11, {8, 3}: -2,
		{1, 4}: +7, {2, 4}: +4,
		{9, 4}: -1,
		{17, 5}: +25, {18, 5}: +7,
		{17, 6}: -11, {18, 6}: +15,
		{1, 15}: +9, {2, 15}: -8,
		{17, 15}: -8, {18, 15}: +9,
		{1, 16}: +8,
		{18, 16}: +8,
		{2, 17}: -3, {3, 17}: -2, {16, 17}: -1, {17, 17}: -3,
	}

	got := renderMultiContourFolderCurve(20, 20)
	skia := loadGoldenPNG(t, "stroke-expanded-fill-20x20.png")
	w, h := 20, 20
	failed := false

	for y := range h {
		for x := range w {
			ourR := int(got.RGBAAt(x, y).R)
			skiaR := int(skia.RGBAAt(x, y).R)
			actualDiff := ourR - skiaR

			expected, known := expectedDiffR[[2]int{x, y}]
			if known {
				if actualDiff != expected {
					t.Errorf("(%d,%d): diff changed: got %+d, expected %+d", x, y, actualDiff, expected)
					failed = true
				}
			} else if actualDiff != 0 {
				t.Errorf("(%d,%d): unexpected diff %+d (not in known diff table)", x, y, actualDiff)
				failed = true
			}
		}
	}

	if !failed {
		t.Logf("PASS: all %d known Skia AAA diffs match exactly (max R diff: 25)", len(expectedDiffR))
	}
}

// TestMultiContourCurveVsFlatten compares forward-diff against geometric
// flattening with per-pixel exact diff verification.
//
// 20 pixels differ (max 7) — all on QuadTo curve corners.
// Forward-diff with deviation-based subdivision uses adaptive segment counts.
// Geometric flattening uses recursive De Casteljau (0.1px tolerance).
// Straight edges: diff==0 (identical coverage).
func TestMultiContourCurveVsFlatten(t *testing.T) {
	expectedDiffR := map[[2]int]int{
		// Top-left corner
		{2, 2}: +7, {3, 2}: +2, {7, 2}: +5,
		{1, 3}: +3, {2, 3}: -6, {8, 3}: -2,
		{2, 4}: -1,
		// Top-right corner
		{18, 5}: +1,
		{17, 6}: -3, {18, 6}: +3,
		// Bottom-left corner
		{1, 15}: +2, {2, 15}: -3,
		{2, 16}: +6,
		// Bottom-right corner
		{17, 15}: -3, {18, 15}: +2,
		{17, 16}: +6,
		// Bottom edge
		{2, 17}: -6, {3, 17}: -1, {16, 17}: -1, {17, 17}: -6,
	}

	curve := renderMultiContourFolderCurve(20, 20)
	flat := renderMultiContourFolder(20, 20)
	w, h := 20, 20
	failed := false

	for y := range h {
		for x := range w {
			curveR := int(curve.RGBAAt(x, y).R)
			flatR := int(flat.RGBAAt(x, y).R)
			actualDiff := curveR - flatR

			expected, known := expectedDiffR[[2]int{x, y}]
			if known {
				if actualDiff != expected {
					t.Errorf("(%d,%d): diff changed: got %+d, expected %+d", x, y, actualDiff, expected)
					failed = true
				}
			} else if actualDiff != 0 {
				t.Errorf("(%d,%d): unexpected diff %+d", x, y, actualDiff)
				failed = true
			}
		}
	}

	if !failed {
		t.Logf("PASS: all %d known curve-vs-flatten diffs match exactly (max R diff: 7)", len(expectedDiffR))
	}
}

// BenchmarkMultiContourFlattenTrue benchmarks geometric flattening mode.
func BenchmarkMultiContourFlattenTrue(b *testing.B) {
	path := buildExpandedFolderPath()
	buf := make([]uint8, 20*20)
	b.ResetTimer()
	for b.Loop() {
		eb := NewEdgeBuilder(2)
		eb.SetFlattenCurves(true)
		eb.BuildFromPath(path, IdentityTransform{})
		FillToBuffer(eb, 20, 20, FillRuleNonZero, buf)
	}
}

// BenchmarkMultiContourFlattenFalse benchmarks forward-diff curve mode.
func BenchmarkMultiContourFlattenFalse(b *testing.B) {
	path := buildExpandedFolderPath()
	buf := make([]uint8, 20*20)
	b.ResetTimer()
	for b.Loop() {
		eb := NewEdgeBuilder(2)
		eb.SetFlattenCurves(false)
		eb.BuildFromPath(path, IdentityTransform{})
		FillToBuffer(eb, 20, 20, FillRuleNonZero, buf)
	}
}

func renderMultiContourFolderCurve(w, h int) *image.RGBA {
	path := buildExpandedFolderPath()

	eb := NewEdgeBuilder(2)
	eb.SetFlattenCurves(false)
	eb.BuildFromPath(path, IdentityTransform{})

	return compositeFolder(eb, w, h)
}

func renderMultiContourFolder(w, h int) *image.RGBA {
	path := buildExpandedFolderPath()

	eb := NewEdgeBuilder(2)
	eb.SetFlattenCurves(true)
	eb.BuildFromPath(path, IdentityTransform{})

	return compositeFolder(eb, w, h)
}

func compositeFolder(eb *EdgeBuilder, w, h int) *image.RGBA {
	coverageBuf := make([]uint8, w*h)
	FillToBuffer(eb, w, h, FillRuleNonZero, coverageBuf)

	bgR, bgG, bgB := uint8(0x3C), uint8(0x3F), uint8(0x41)
	fR, fG, fB, fA := uint16(0xCE), uint16(0xD0), uint16(0xD6), uint16(0xFF)

	img := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := range h {
		for x := range w {
			cov := uint16(coverageBuf[y*w+x])
			if cov == 0 {
				img.SetRGBA(x, y, color.RGBA{R: bgR, G: bgG, B: bgB, A: 0xFF})
				continue
			}
			scale := cov + 1
			srcR := uint8((fR * scale) >> 8)
			srcG := uint8((fG * scale) >> 8)
			srcB := uint8((fB * scale) >> 8)
			srcA := uint8((fA * scale) >> 8)
			invScale := (255 - uint16(srcA)) + 1
			dstR := srcR + uint8((uint16(bgR)*invScale)>>8)
			dstG := srcG + uint8((uint16(bgG)*invScale)>>8)
			dstB := srcB + uint8((uint16(bgB)*invScale)>>8)
			img.SetRGBA(x, y, color.RGBA{R: dstR, G: dstG, B: dstB, A: 0xFF})
		}
	}
	return img
}

func buildExpandedFolderPath() PathLike {
	verbs := []PathVerb{
		MoveTo, LineTo, LineTo, LineTo, LineTo, LineTo,
		QuadTo, LineTo, QuadTo, LineTo, QuadTo, LineTo, QuadTo, LineTo, QuadTo, LineTo, Close,
		MoveTo, LineTo, QuadTo, LineTo, QuadTo, QuadTo, LineTo, QuadTo, LineTo, QuadTo, LineTo, QuadTo, LineTo, LineTo, LineTo, Close,
	}
	points := []float32{
		10.84, 5.1921, 11.0486, 5.3659, 10.7285, 5.75,
		10.7285, 5.25, 11, 5.25, 17, 5.25,
		18.75, 5.25, 18.75, 7,
		18.75, 15.1667,
		18.75, 17.25, 16.75, 17.25,
		3.25, 17.25,
		1.25, 17.25, 1.25, 15.1667,
		1.25, 4.8333,
		1.25, 2.75, 3.25, 2.75,
		7.6379, 2.75,
		7.9095, 2.75, 8.1181, 2.9238,
		10.84, 5.1921,
		10.1998, 5.9603, 7.4779, 3.6921,
		7.5475, 3.75, 7.6379, 3.75,
		3.25, 3.75,
		2.8507, 3.75, 2.5579, 4.052,
		2.25, 4.3696, 2.25, 4.8333,
		2.25, 15.1667,
		2.25, 16.25, 3.25, 16.25,
		16.75, 16.25,
		17.75, 16.25, 17.75, 15.1667,
		17.75, 7,
		17.75, 6.25, 17, 6.25,
		11, 6.25, 10.5475, 6.25, 10.1998, 5.9603,
	}
	return NewScenePathAdapter(false, verbs, points)
}
