// Copyright 2026 The gogpu Authors
// SPDX-License-Identifier: BSD-3-Clause

package velloport

import (
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"testing"

	"github.com/gogpu/gg/internal/raster"
	"github.com/gogpu/gg/scene"
)

// goldenTest defines a test case with parameters matching an upstream Vello scene.
type goldenTest struct {
	Name      string
	Width     int
	Height    int
	FillColor color.RGBA
	BgColor   color.RGBA // Background color
	FillRule  FillRule
	// BuildPath uses EdgeBuilder for curves (circles).
	BuildPath func(eb *raster.EdgeBuilder)
	// BuildLines generates LineSoup directly — includes ALL lines
	// (including horizontal), matching Vello's flattener behavior.
	BuildLines func() []LineSoup
	Threshold  float64
}

// gpuPipelineTests returns test cases for the Vello CPU pipeline.
// Golden images generated by running Vello with use_cpu: true (vello-gpu-golden utility).
// Velloport is a Go port of vello_shaders/src/cpu/ — the SAME algorithm (CPU-CPU comparison).
//
// Scenes match: sparse_strips/vello_sparse_tests/tests/basic.rs parameters,
// rendered through the CPU pipeline (fine.rs, not GPU shaders).
func gpuPipelineTests() []goldenTest {
	white := color.RGBA{R: 255, G: 255, B: 255, A: 255}
	lime := color.RGBA{R: 0, G: 255, B: 0, A: 255}
	maroon := color.RGBA{R: 128, G: 0, B: 0, A: 255}
	return []goldenTest{
		{
			Name:      "filled_circle",
			Width:     100,
			Height:    100,
			FillColor: lime,
			BgColor:   white,
			FillRule:  FillRuleNonZero,
			Threshold: 0.0, // CPU-CPU: pixel-perfect (Euler Spiral flatten + pipeline stages)
			BuildLines: func() []LineSoup {
				// Vello Euler Spiral flatten of Circle((50,50), 45)
				return FlattenFill(circleCubics(50, 50, 45))
			},
		},
		{
			Name:      "filled_triangle",
			Width:     100,
			Height:    100,
			FillColor: lime,
			BgColor:   white,
			FillRule:  FillRuleNonZero,
			Threshold: 0.0, // CPU-CPU: pixel-perfect (straight lines)
			BuildLines: func() []LineSoup {
				return polygonToLineSoup([][2]float32{
					{5, 5}, {95, 50}, {5, 95},
				})
			},
		},
		{
			Name:      "filling_nonzero_rule",
			Width:     100,
			Height:    100,
			FillColor: maroon,
			BgColor:   white,
			FillRule:  FillRuleNonZero,
			Threshold: 0.15, // CPU-CPU: 8px (0.08%) at float32 rounding boundaries (Rust vs Go)
			BuildLines: func() []LineSoup {
				return polygonToLineSoup([][2]float32{
					{50, 10}, {75, 90}, {10, 40}, {90, 40}, {25, 90},
				})
			},
		},
		{
			Name:      "filling_evenodd_rule",
			Width:     100,
			Height:    100,
			FillColor: maroon,
			BgColor:   white,
			FillRule:  FillRuleEvenOdd,
			Threshold: 0.15, // CPU-CPU: 10px (0.10%) at float32 rounding boundaries (Rust vs Go)
			BuildLines: func() []LineSoup {
				return polygonToLineSoup([][2]float32{
					{50, 10}, {75, 90}, {10, 40}, {90, 40}, {25, 90},
				})
			},
		},
	}
}

// gpuPipelineSmokeTests returns 20x20 smoke test scenes from vello_tests/snapshots/smoke/.
func gpuPipelineSmokeTests() []goldenTest {
	black := color.RGBA{R: 0, G: 0, B: 0, A: 255}
	blue := color.RGBA{R: 0, G: 0, B: 255, A: 255}
	return []goldenTest{
		{
			Name:      "smoke_filled_circle",
			Width:     20,
			Height:    20,
			FillColor: blue,
			BgColor:   black,
			FillRule:  FillRuleNonZero,
			Threshold: 0.0, // CPU-CPU: pixel-perfect (Euler Spiral flatten)
			BuildLines: func() []LineSoup {
				// Vello Euler Spiral flatten of Circle((10,10), 7)
				return FlattenFill(circleCubics(10, 10, 7))
			},
		},
		{
			Name:      "smoke_filled_square",
			Width:     20,
			Height:    20,
			FillColor: blue,
			BgColor:   black,
			FillRule:  FillRuleNonZero,
			Threshold: 0.0, // CPU-CPU: pixel-perfect (straight lines)
			BuildLines: func() []LineSoup {
				return polygonToLineSoup([][2]float32{
					{7, 7}, {13, 7}, {13, 13}, {7, 13},
				})
			},
		},
	}
}

// circleCubics returns a circle as 4 cubic Bezier curves (standard SVG/PDF representation).
// This matches kurbo's Circle.to_path() — 4 quadrant arcs approximated by cubics.
func circleCubics(cx, cy, r float32) []CubicBezier {
	// kappa = 4/3 * (sqrt(2) - 1) ≈ 0.5522847498
	const kappa float32 = 0.5522847498
	k := r * kappa
	return []CubicBezier{
		// Right → Bottom (quadrant 1: 0° → 90°)
		{P0: [2]float32{cx + r, cy}, P1: [2]float32{cx + r, cy + k}, P2: [2]float32{cx + k, cy + r}, P3: [2]float32{cx, cy + r}},
		// Bottom → Left (quadrant 2: 90° → 180°)
		{P0: [2]float32{cx, cy + r}, P1: [2]float32{cx - k, cy + r}, P2: [2]float32{cx - r, cy + k}, P3: [2]float32{cx - r, cy}},
		// Left → Top (quadrant 3: 180° → 270°)
		{P0: [2]float32{cx - r, cy}, P1: [2]float32{cx - r, cy - k}, P2: [2]float32{cx - k, cy - r}, P3: [2]float32{cx, cy - r}},
		// Top → Right (quadrant 4: 270° → 360°)
		{P0: [2]float32{cx, cy - r}, P1: [2]float32{cx + k, cy - r}, P2: [2]float32{cx + r, cy - k}, P3: [2]float32{cx + r, cy}},
	}
}

// pairsToLineSoup converts explicit line segment pairs to LineSoup.
func pairsToLineSoup(pairs [][2][2]float32) []LineSoup {
	lines := make([]LineSoup, 0, len(pairs))
	for _, p := range pairs {
		if p[0][0] == p[1][0] && p[0][1] == p[1][1] {
			continue
		}
		lines = append(lines, LineSoup{PathIx: 0, P0: p[0], P1: p[1]})
	}
	return lines
}

// polygonToLineSoup generates LineSoup from polygon vertices directly.
func polygonToLineSoup(vertices [][2]float32) []LineSoup {
	n := len(vertices)
	if n < 2 {
		return nil
	}
	lines := make([]LineSoup, 0, n)
	for i := 0; i < n; i++ {
		p0 := vertices[i]
		p1 := vertices[(i+1)%n]
		if p0[0] == p1[0] && p0[1] == p1[1] {
			continue
		}
		lines = append(lines, LineSoup{PathIx: 0, P0: p0, P1: p1})
	}
	return lines
}

// scenePathAdapter wraps scene.Path to implement raster.PathLike.
type scenePathAdapter struct{ path *scene.Path }

func (a *scenePathAdapter) IsEmpty() bool     { return a.path.IsEmpty() }
func (a *scenePathAdapter) Points() []float32 { return a.path.Points() }
func (a *scenePathAdapter) Verbs() []raster.PathVerb {
	sv := a.path.Verbs()
	rv := make([]raster.PathVerb, len(sv))
	for i, v := range sv {
		rv[i] = raster.PathVerb(v)
	}
	return rv
}

func buildEdgesFromScenePath(eb *raster.EdgeBuilder, p *scene.Path) {
	eb.BuildFromPath(&scenePathAdapter{path: p}, raster.IdentityTransform{})
}

func gpuPipelineGoldenPath(name string) string {
	return filepath.Join("..", "..", "..", "testdata", "golden", "vello-gpu-pipeline", name+".png")
}

func loadGoldenFile(t *testing.T, path string) *image.RGBA {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Skipf("golden file not found: %v", err)
		return nil
	}
	defer f.Close()
	img, err := png.Decode(f)
	if err != nil {
		t.Fatalf("failed to decode %s: %v", path, err)
	}
	rgba := image.NewRGBA(img.Bounds())
	for y := img.Bounds().Min.Y; y < img.Bounds().Max.Y; y++ {
		for x := img.Bounds().Min.X; x < img.Bounds().Max.X; x++ {
			rgba.Set(x, y, img.At(x, y))
		}
	}
	return rgba
}

func renderWithVelloPort(tc goldenTest) *image.RGBA {
	var lines []LineSoup

	if tc.BuildLines != nil {
		lines = tc.BuildLines()
	} else {
		eb := raster.NewEdgeBuilder(2) // 4x AA
		tc.BuildPath(eb)
		vlines := eb.VelloLines()
		lines = make([]LineSoup, len(vlines))
		for i, vl := range vlines {
			lines[i] = LineSoupFromVelloLine(vl.P0, vl.P1, vl.IsDown)
		}
	}

	r := NewRasterizer(tc.Width, tc.Height)
	alphas := r.Rasterize(lines, tc.FillRule)

	img := image.NewRGBA(image.Rect(0, 0, tc.Width, tc.Height))
	fc := tc.FillColor
	bg := tc.BgColor
	for y := 0; y < tc.Height; y++ {
		for x := 0; x < tc.Width; x++ {
			alpha := alphas[y*tc.Width+x]
			if alpha <= 0 {
				img.Set(x, y, bg)
				continue
			}
			if alpha > 1.0 {
				alpha = 1.0
			}
			a := alpha
			cr := uint8(float32(fc.R)*a + float32(bg.R)*(1-a) + 0.5)
			cg := uint8(float32(fc.G)*a + float32(bg.G)*(1-a) + 0.5)
			cb := uint8(float32(fc.B)*a + float32(bg.B)*(1-a) + 0.5)
			img.Set(x, y, color.RGBA{R: cr, G: cg, B: cb, A: 255})
		}
	}
	return img
}

func compareImages(img1, img2 *image.RGBA) (diffPercent float64, diffCount int) {
	bounds := img1.Bounds()
	totalPixels := bounds.Dx() * bounds.Dy()
	for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
		for x := bounds.Min.X; x < bounds.Max.X; x++ {
			c1 := img1.RGBAAt(x, y)
			c2 := img2.RGBAAt(x, y)
			if c1.R != c2.R || c1.G != c2.G || c1.B != c2.B || c1.A != c2.A {
				diffCount++
			}
		}
	}
	diffPercent = float64(diffCount) / float64(totalPixels) * 100
	return
}

func saveDiffImage(t *testing.T, prefix, name string, ours, reference *image.RGBA) {
	t.Helper()
	tmpDir := filepath.Join("..", "..", "..", "tmp")
	_ = os.MkdirAll(tmpDir, 0o755)

	diffImg := image.NewRGBA(ours.Bounds())
	for y := ours.Bounds().Min.Y; y < ours.Bounds().Max.Y; y++ {
		for x := ours.Bounds().Min.X; x < ours.Bounds().Max.X; x++ {
			v := ours.RGBAAt(x, y)
			g := reference.RGBAAt(x, y)
			if v.R != g.R || v.G != g.G || v.B != g.B {
				diffImg.Set(x, y, color.RGBA{R: 255, G: 0, B: 0, A: 255})
			} else {
				gray := uint8((uint32(v.R) + uint32(v.G) + uint32(v.B)) / 3)
				diffImg.Set(x, y, color.RGBA{R: gray, G: gray, B: gray, A: 255})
			}
		}
	}

	diffPath := filepath.Join(tmpDir, prefix+"_diff_"+name+".png")
	if f, err := os.Create(diffPath); err == nil {
		_ = png.Encode(f, diffImg)
		f.Close()
		t.Logf("Diff image saved: %s", diffPath)
	}

	oursPath := filepath.Join(tmpDir, prefix+"_ours_"+name+".png")
	if f, err := os.Create(oursPath); err == nil {
		_ = png.Encode(f, ours)
		f.Close()
		t.Logf("Our output saved: %s", oursPath)
	}
}

// TestVelloPortVsGPUPipeline compares velloport output against Vello CPU pipeline
// reference images. This is a SAME-ALGORITHM comparison: velloport ports
// vello_shaders/src/cpu/ and golden images are generated with use_cpu: true.
//
// Golden images generated by vello-gpu-golden Rust utility (Vello CPU path: fine.rs).
// Golden dir: testdata/golden/vello-gpu-pipeline/
func TestVelloPortVsGPUPipeline(t *testing.T) {
	tests := gpuPipelineTests()
	for _, tc := range tests {
		t.Run(tc.Name, func(t *testing.T) {
			reference := loadGoldenFile(t, gpuPipelineGoldenPath(tc.Name))
			if reference == nil {
				return
			}

			if reference.Bounds().Dx() != tc.Width || reference.Bounds().Dy() != tc.Height {
				t.Fatalf("golden image %dx%d does not match expected %dx%d",
					reference.Bounds().Dx(), reference.Bounds().Dy(), tc.Width, tc.Height)
			}

			ours := renderWithVelloPort(tc)
			diffPercent, diffCount := compareImages(ours, reference)

			t.Logf("Scene: %s, Size: %dx%d, Diff: %d pixels (%.2f%%), Threshold: %.1f%%",
				tc.Name, tc.Width, tc.Height, diffCount, diffPercent, tc.Threshold)

			saveDiffImage(t, "velloport_gpu", tc.Name, ours, reference)

			if diffPercent > tc.Threshold {
				t.Errorf("FAIL: %.2f%% pixel difference exceeds threshold %.2f%%", diffPercent, tc.Threshold)
			}
		})
	}
}

// TestVelloPortVsGPUPipelineSmoke compares against 20x20 CPU pipeline smoke tests.
// These are smaller scenes that amplify any differences.
func TestVelloPortVsGPUPipelineSmoke(t *testing.T) {
	tests := gpuPipelineSmokeTests()
	for _, tc := range tests {
		t.Run(tc.Name, func(t *testing.T) {
			reference := loadGoldenFile(t, gpuPipelineGoldenPath(tc.Name))
			if reference == nil {
				return
			}

			if reference.Bounds().Dx() != tc.Width || reference.Bounds().Dy() != tc.Height {
				t.Fatalf("golden image %dx%d does not match expected %dx%d",
					reference.Bounds().Dx(), reference.Bounds().Dy(), tc.Width, tc.Height)
			}

			ours := renderWithVelloPort(tc)
			diffPercent, diffCount := compareImages(ours, reference)

			t.Logf("Scene: %s, Size: %dx%d, Diff: %d pixels (%.2f%%), Threshold: %.1f%%",
				tc.Name, tc.Width, tc.Height, diffCount, diffPercent, tc.Threshold)

			saveDiffImage(t, "velloport_smoke", tc.Name, ours, reference)

			if diffPercent > tc.Threshold {
				t.Errorf("FAIL: %.2f%% pixel difference exceeds threshold %.2f%%", diffPercent, tc.Threshold)
			}
		})
	}
}
